###
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{    
    "name" : "미들웨어g",
    "phone_number" : "010-2345-111122822",
    "gender" : "남자"    
}

###
GET http://localhost:3000/user/61addfaa113a7f605033157e HTTP/1.1
61addfaa113a7f605033157e


###
DELETE http://localhost:3000/user/61adf6fd6108682261072889 HTTP/1.1

###
PUT http://localhost:3000/user/61addeeb5157024ec70272f1 HTTP/1.1
Content-Type: application/json

{    
    "name" : "111111"
}

###########################

###
POST http://localhost:3000/post HTTP/1.1
Content-Type: application/json

{    
    "user" : "홍길동",
    "title" : "게시글제목2",
    "body" : "블라블라2"    
}

###
POST http://localhost:3000/post HTTP/1.1
Content-Type: application/json

{    
    "user" : "홍길동",
    "title" : "게시글제목2",
    "body" : "블라블라2"    
}

###
GET http://localhost:3000/post/61c2f3c5fa23c704b972a41f HTTP/1.1

###
DELETE http://localhost:3000/post/61c2f3c5fa23c704b972a41f HTTP/1.1

###
PUT http://localhost:3000/post/61c2f3fffa23c704b972a421 HTTP/1.1
Content-Type: application/json

{    
    "title" : "제목수정해보자"
}
